#!/bin/tcsh
#
# Climatology:
# Start a climatology run with Jan 1-5.
#
 set model_root = /glade/u/home/nikhilr/tiegcm_func/tiegcm2.0
 set execute = yes
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#
# Climatology smax,smin at res5.0:
#
./tgcmrun -run_name=climatology_smax -model_name=tiegcm -model_res=5.0 -submit=yes \
  -stdout_dir=tiegcm_res5.0_climatology_smax -model_root=$model_root -execute=$execute
./tgcmrun -run_name=climatology_smin -model_name=tiegcm -model_res=5.0 -submit=yes \
  -stdout_dir=tiegcm_res5.0_climatology_smin -model_root=$model_root -execute=$execute
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#
# Climatology smax,smin at res2.5:
#
./tgcmrun -run_name=climatology_smax -model_name=tiegcm -model_res=2.5 -submit=yes \
  -stdout_dir=tiegcm_res2.5_climatology_smax -model_root=$model_root -execute=$execute
./tgcmrun -run_name=climatology_smin -model_name=tiegcm -model_res=2.5 -submit=yes \
  -stdout_dir=tiegcm_res2.5_climatology_smin -model_root=$model_root -execute=$execute
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

