#!/bin/tcsh
#
# Climatology:
#
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#
# Climatology smax,smin at res5.0:
#
tgcmrun -run_name climatology_smax -model_name tiegcm -model_res 5.0 -submit yes -execute yes \
  -stdout_dir tiegcm_res5.0_climatology
#tgcmrun -run_name climatology_smin -model_name tiegcm -model_res 5.0 -submit yes -execute yes \
#  -stdout_dir tiegcm_res5.0_climatology
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
#
# Climatology smax,smin at res2.5:
#
tgcmrun -run_name climatology_smax -model_name tiegcm -model_res 2.5 -submit yes -execute yes \
  -stdout_dir tiegcm_res2.5_climatology
#tgcmrun -run_name climatology_smin -model_name tiegcm -model_res 2.5 -submit yes -execute yes \
#  -stdout_dir tiegcm_res2.5_climatology
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

