#! /bin/csh
#
# Set up a tiegcm job for days 329-359, 2006, i.e., "AGU Storm" case.
# Run may be heelis potential model with GPI data, or weimer potential 
#   with IMF/OMNI solar wind + GPI(f107) data.
#
set case       = dec2006                      # AGU Storm case
set model      = tiegcm                       # Model name namelist and job scripts
#set modeldir   = tiegcm_trunk                 # model root dir (access to mknamelist, mkjob scripts)
 set modeldir   = ..                           # if executed from a modeldir/tests directory
set mknamelist = $modeldir/scripts/mknamelist  # mknamelist script
set mkjob      = $modeldir/scripts/mkjob       # mkjob script
set utildir    = $modeldir/scripts             # for job script
set system     = linux                         # "linux" or "ibm"
set execdir    = ${model}-${system}            # for job script
set template   = $modeldir/scripts/job_${system}.txt # for mkjob
#
# LSF BSUB parameters (ignored if system is linux):
set bsub_project = 24100004               # your account number on NCAR IBM machine
set bsub_queue   = regular
set bsub_nproc   = 32
set bsub_wallclock = "2:00"
set bsub_jobname = $case
#
set modelres = 5.0                        # resolution is either 5.0 or 2.5
set potential_name  = "heelis"            # potential model, "heelis" or "weimer"
set TGCMDATA = '$TGCMDATA'
set start_year = 2006
set start_day  = 329
set stop_day   = 359
set source = "'$TGCMDATA/TGCM.tiegcm1.93.p_gpi_dec2006_001.nc'"
set source_start = "${start_day},0,0"
#
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
if ($potential_name != "heelis" && $potential_name != "weimer") then
  echo ">>> Bad potential_name: $potential_name (Must be either 'heelis' or 'weimer')"
  exit
endif
set potential_model = "'HEELIS'"
set data_name = 'gpi'
if ($potential_name == "weimer") then
  set potential_model = "'WEIMER'" 
  set data_name = 'imf'
endif
#
set output1 = "'${model}.p_${data_name}_${case}_${potential_name}_001.nc','to',"
set output2 = "'${model}.p_${data_name}_${case}_${potential_name}_004.nc','by','1'"
set output = "${output1}${output2}"
set mxhist_prim = 10
set secout1 = "'${model}.s_${data_name}_${case}_${potential_name}_001.nc','to',"
set secout2 = "'${model}.s_${data_name}_${case}_${potential_name}_015.nc','by','1'"
set secout = "${secout1}${secout2}"
set mxhist_sech = 48
#
# Make heelis namelist:
#
if ($potential_name == "heelis") then
  $mknamelist -model=$model -fileout=${model}_${data_name}_${case}_${potential_name}.inp \
    -START_YEAR=$start_year -START_DAY=$start_day -SOURCE=$source -SOURCE_START="${source_start},0,0" \
    -START="${start_day},0,0" -STOP="${stop_day},0,0" -HIST="1,0,0" \
    -MXHIST_PRIM=$mxhist_prim -MXHIST_SECH=$mxhist_sech \
    -OUTPUT=$output -SECOUT=$secout -POTENTIAL_MODEL=$potential_model \
    -SECSTART="${start_day},1,0" -SECSTOP="${stop_day},0,0" -SECHIST="0,1,0" \
    -uncomment="GPI_NCFILE" -comment="CTPOTEN" -comment="POWER" -comment="F107" -comment="F107A"
#
# Make weimer namelist:
else
  $mknamelist -model=$model -fileout=${model}_${data_name}_${case}_${potential_name}.inp \
    -START_YEAR=$start_year -START_DAY=$start_day -SOURCE=$source -SOURCE_START="${source_start},0,0" \
    -START="${start_day},0,0" -STOP="${stop_day},0,0" -HIST="1,0,0" \
    -MXHIST_PRIM=$mxhist_prim -MXHIST_SECH=$mxhist_sech \
    -OUTPUT=$output -SECOUT=$secout -POTENTIAL_MODEL=$potential_model \
    -SECSTART="${start_day},1,0" -SECSTOP="${stop_day},0,0" -SECHIST="0,1,0" \
    -comment="CTPOTEN" -comment="POWER" -comment="F107" -comment="F107A" \
    -uncomment="IMF_NCFILE" -BXIMF=$bximf -BYIMF=$byimf -BZIMF=$bzimf -SWVEL=$swvel -SWDEN=$swden
endif
#
# Make job script:
#
$mkjob -model=$model -fileout=${model}_${data_name}_${case}_${potential_name}_$system.job \
  -bsub_jobname=$bsub_jobname -system=$system -utildir=$utildir -execdir=$execdir \
  -bsub_project=$bsub_project -bsub_queue=$bsub_queue -bsub_nproc=$bsub_nproc \
  -bsub_wallclock=$bsub_wallclock \
  -template=$template -modeldir="$modeldir" -modelres=$modelres \
  -input="${model}_${data_name}_${case}_${potential_name}.inp" \
  -output="${model}_${data_name}_${case}_${potential_name}.out"
