#!/usr/bin/perl
#
# Change #include statements from "" to <>, or vice-versa
#
use Getopt::Long;
use File::Copy;
$to = "brackets";
$overwrite = 0;
&GetOptions(
   "to:s"        => \$to,
   "overwrite"   => \$overwrite
) or die "Error parsing args..\n";
if ($to ne "brackets" and $to ne "quotes") {
  die "Please set option -to to either 'brackets' or 'quotes'\n"; }
if ($to eq "brackets") {
  print "Will change #include statements from quotes to brackets..\n";
} else {
  print "Will change #include statements from brackets to quotes..\n";
}
if ($overwrite) {
  print "Will overwrite source files.\n";
} else {
  print "Will NOT overwrite source files (new files will be named file.new)\n";
}
if (! @ARGV) { die "No source files??\n"; }
#
while (@ARGV) {
  $srcfile = shift;
  print "\nSource file = $srcfile\n";
#
# Save original source file with .old suffix and remove original file:
  copy($srcfile,"$srcfile.old") || 
    die "Error copying source file $srcfile to $srcfile.old\n";
#
# Open copied source file for read only:
  open(SRCFILE,"<$srcfile") or die "Could not open $srcfile\n";
#
# Open new source file for writing:
  $newfile = "$srcfile.new";
  open(NEWFILE,">$newfile") or die "Could not open $newfile\n";
#
# Read source file:
  while (<SRCFILE>) {
    $line = $_;
#
# Change from quotes to brackets:
    if ($to eq "brackets") {
      if ($line =~ /^#include\s+["'](.*)["']/) {
        $newinclude = "#include <$1>";
        print NEWFILE "$newinclude\n";
        print "  Changing quoted include of $1 to: $newinclude\n";
      } else {
        print NEWFILE "$line";
      }
#
# Change from brackets to quotes:
    } elsif ($to eq "quotes") { 
      if (/^#include\s+[<](.*)[>]/ ) {
        $newinclude = "#include \"$1\"";
        print NEWFILE "$newinclude\n";
        print "  Changing bracketed include of $1 to: $newinclude\n"; 
      } else {
        print NEWFILE "$line";
      }
    }
  } # while SRCFILE
  close NEWFILE;
  close SRCFILE;
  if ($overwrite) {
    rename "$srcfile.new",$srcfile || 
      die "Error moving $srcfile.new to $srcfile\n";
    print "  Overwrote source file $srcfile\n";
  } else {
    print "  Wrote new source file $srcfile.new\n";
  }
} # while ARGV
