#!/usr/bin/env python3
import sys

def strip_non_ascii(string):
    '''Returns the string without non-ASCII characters'''
    stripped = (c for c in string if 0 < ord(c) < 127)
    return ''.join(stripped)

if len(sys.argv) == 1:
    print('>>> Please provide input files from which to remove non-ASCII characters.')
    sys.exit()

for infile in sys.argv[1:]:
    # Using with statement to ensure proper file closure
    with open(infile, 'r', encoding='utf-8', errors='ignore') as f:
        lines = f.readlines()
        lines = [line.rstrip() for line in lines]

    # Overwrite input file:
    with open(infile, 'w', encoding='utf-8') as f:
        print(f'Overwriting file {infile} with non-ASCII characters removed.')
        for line in lines:
            newline = strip_non_ascii(line)
            f.write(newline + '\n')

    # If you want to write to an output file instead of overwriting the input file, uncomment below:
    # outfile = infile + '.txt'
    # with open(outfile, 'w', encoding='utf-8') as f:
    #     print(f'Writing file {outfile}')
    #     for line in lines:
    #         newline = strip_non_ascii(line)
    #         f.write(newline + '\n')

