#!/bin/tcsh
#
#PBS -N tiegcm
#PBS -A P28100036
##PBS -A NHAO0004
#PBS -q regular
#PBS -o tiegcm.out
#PBS -j oe
#PBS -m abe
#PBS -M wiltbemj@ucar.edu
#PBS -l walltime=00:30:00
#
# Recommended for double-res (2.5 deg) tiegcm: 
# -n64,ptile=16 (4 nodes, 16 procs/node)
# Note: -n 1 is permitted.
# For 2.5-deg res, STEP= 30, nproc=64, allow 8.5 mins per simulated day (0.17 secs/step)
# For 2.5-deg res, STEP= 60, nproc=64, allow 4.5 mins per simulated day (0.17 secs/step)
#
#  (2 nodes, 32 procs/node)
#PBS -l select=2:ncpus=36:mpiprocs=36
#
  setenv TGCMDATA /glade/p/hao/tgcm/data/tiegcm2.0
  setenv MP_LABELIO YES
  setenv MP_SHARED_MEMORY yes
#
# Execute:
  mpiexec_mpt -p "%g:" /glade/scratch/wiltbemj/tiegcm-master/tiegcm.exec/tiegcm.exe /glade/u/home/wiltbemj/src/tiegcm/scripts/tiegcm_res2.5_default.inp >&! /glade/work/wiltbemj/src/tiegcm/scripts/tiegcm.out
#
# Save stdout:
  /glade/u/home/wiltbemj/src/tiegcm/scripts/rmbinchars /glade/work/wiltbemj/src/tiegcm/scripts/tiegcm.out # remove any non-ascii chars in stdout file
  /glade/u/home/wiltbemj/src/tiegcm/scripts/mklogs /glade/work/wiltbemj/src/tiegcm/scripts/tiegcm.out     # break stdout into per-task log files
  cd /glade/work/wiltbemj/src/tiegcm/scripts
#
# Make tar file of task log files:
  tar -cf /glade/work/wiltbemj/src/tiegcm/scripts/tiegcm.out.tar *task*.out 
  echo Saved stdout tar file /glade/work/wiltbemj/src/tiegcm/scripts/tiegcm.out.tar 
  rm *task*.out
