#!/usr/bin/perl
$system   = "linux";       # "ibm" or "linux" system (see mkjob)
$modeldir = "tiegcm_trunk";
$modelname= "tiegcm";
$utildir  = "$modeldir/scripts";
$template = "$utildir/job_$system.txt";  # job template (for mkjob)
$user     = $ENV{USER};
$source   = '\"\$TGCMDATA/TGCM.tiegcm1.93.pcntr_eqnx_smin.nc\"';
#
# LSF directives for ibm job:
$bsub_project = 24100004;
$bsub_queue    = "regular";
$bsub_wallclock= "0:30";
#
@nprocs = (1,4,8,16,32,48,64);
foreach $nproc (@nprocs) {
# print "nproc=$nproc\n";
  $snproc = $nproc;
  if ($snproc < 10) { $snproc = "0" . $nproc; };

  $dir = $modelname . "_nproc" . $snproc;
  if (! -d $dir) { mkdir $dir || die ">>> Error from mkdir $dir\n"; }

  $jobfile = $modelname . "_nproc" . $snproc . ".job";
  $input   = "$dir/$modelname" . "_nproc" . $snproc . ".inp";
  $output  = "$dir/$modelname" . "_nproc" . $snproc . ".out";
  $execdir = "$dir/$modelname" . "_nproc" . $snproc . "-" . $system;
#
# Make job script:
#
  $command = "$utildir/mkjob -modeldir=$modeldir -modelname=$modelname -fileout=$jobfile -system=$system " . 
    " -template=$template -utildir=$utildir -execdir=$execdir -input=$input " .
    " -output=$output -nproc=$nproc"; 
  if ($system eq 'ibm') {
    $jobname = "nproc" . $nproc;
    $command = $command . " -bsub_jobname=$jobname -bsub_project=$bsub_project" .
      " -bsub_queue=$bsub_queue -bsub_nproc=$nproc -bsub_wallclock=$bsub_wallclock";
  }
# print "Executing $command\n";
  `$command`;
#
# Make namelist input file:
#
# $command = "$utildir/mknamelist -fileout=$dir/$myjob->{namelist} -POWER=$myjob->{power}" . 
#   " -CTPOTEN=$myjob->{ctpoten} -F107=$myjob->{f107} -F107A=$myjob->{f107a}" .
#   " -SOURCE=$myjob->{source} -SOURCE_START=$myjob->{source_start} -START=$myjob->{start}" .
#   " -STOP=$myjob->{stop} -HIST=$myjob->{hist} -SAVE=$myjob->{save} -OUTPUT=$myjob->{output}" .
#   " -SECSTART=$myjob->{secstart} -SECSTOP=$myjob->{secstop} -SECHIST=$myjob->{sechist}" .
#   " -SECSAVE=$myjob->{secsave} -SECOUT=$myjob->{secout} -START_YEAR=$myjob->{start_year}" .
#   " -START_DAY=$myjob->{start_day}";

  $output = '\"' . $modelname . '.p_nproc' . $nproc . '.nc\"';
  $secout = '\"' . $modelname . '.s_nproc' . $nproc . '.nc\"';
  $command = "$utildir/mknamelist -fileout=$input -SOURCE=$source -OUTPUT=$output -SECOUT=$secout";
  `$command`;

} # foreach nproc
